[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = false

[browser]
serverAddress = "0.0.0.0"

[runner]
magicEnabled = true

[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
